import type { GraphDocument } from '@fcw/graph-core';

export function createDemoGraph(): GraphDocument {
  return {
    id: 'demo_001',
    meta: { created: new Date().toISOString(), title: 'Demo Conversation' },
    nodes: {
      n1: {
        id: 'n1',
        type: 'user_prompt',
        content: 'How do I build a WebSocket server in Node.js?',
        position: { x: 0, y: 0 },
        created: new Date().toISOString(),
        status: 'complete',
      },
      n2: {
        id: 'n2',
        type: 'response',
        content: "Here's how to set up a WebSocket server using the `ws` package:\n\n1. Install the package\n2. Create an HTTP server\n3. Attach the WebSocket server\n\nLet me show you the code.",
        position: { x: 0, y: 0 },
        created: new Date().toISOString(),
        status: 'complete',
      },
      n3: {
        id: 'n3',
        type: 'code',
        content: "import { WebSocketServer } from 'ws';\nimport { createServer } from 'http';\n\nconst server = createServer();\nconst wss = new WebSocketServer({ server });\n\nwss.on('connection', (ws) => {\n  ws.on('message', (data) => {\n    console.log('received:', data);\n  });\n  ws.send('Hello from server!');\n});\n\nserver.listen(8080);",
        position: { x: 0, y: 0 },
        created: new Date().toISOString(),
        status: 'complete',
      },
      n4: {
        id: 'n4',
        type: 'tool_call',
        content: 'file_search("ws package documentation")',
        position: { x: 0, y: 0 },
        created: new Date().toISOString(),
        status: 'complete',
      },
      n5: {
        id: 'n5',
        type: 'tool_result',
        content: 'Found: ws@8.16.0 — Simple to use, blazing fast, and thoroughly tested WebSocket client and server for Node.js',
        position: { x: 0, y: 0 },
        created: new Date().toISOString(),
        status: 'complete',
      },
      n6: {
        id: 'n6',
        type: 'thought',
        content: 'The user might also want to know about error handling and reconnection strategies. I should mention those as follow-up topics.',
        position: { x: 0, y: 0 },
        created: new Date().toISOString(),
        status: 'complete',
      },
      n7: {
        id: 'n7',
        type: 'user_prompt',
        content: 'What about error handling?',
        position: { x: 0, y: 0 },
        created: new Date().toISOString(),
        status: 'complete',
      },
      n8: {
        id: 'n8',
        type: 'response',
        content: "Great question! You should handle these key scenarios:\n\n- **Connection errors** — listen for the `'error'` event\n- **Unexpected disconnects** — implement heartbeat with `ping/pong`\n- **Message validation** — always validate incoming data\n\nHere's the pattern...",
        position: { x: 0, y: 0 },
        created: new Date().toISOString(),
        status: 'streaming',
      },
      n9: {
        id: 'n9',
        type: 'summary',
        content: 'Conversation about building WebSocket servers in Node.js with ws package, covering setup, code examples, and error handling.',
        position: { x: 0, y: 0 },
        created: new Date().toISOString(),
        status: 'complete',
      },
      n10: {
        id: 'n10',
        type: 'annotation',
        content: 'TODO: Add reconnection example with exponential backoff',
        position: { x: 0, y: 0 },
        created: new Date().toISOString(),
        status: 'complete',
      },
    },
    edges: [
      { from: 'n1', to: 'n2', type: 'reply_to' },
      { from: 'n2', to: 'n3', type: 'reply_to' },
      { from: 'n2', to: 'n4', type: 'tool_call' },
      { from: 'n4', to: 'n5', type: 'tool_result' },
      { from: 'n2', to: 'n6', type: 'reply_to' },
      { from: 'n1', to: 'n7', type: 'branches_from' },
      { from: 'n7', to: 'n8', type: 'reply_to' },
      { from: 'n1', to: 'n9', type: 'references' },
      { from: 'n8', to: 'n10', type: 'references' },
    ],
  };
}
